import type { Programme } from '@/lib/programmes';
import type { OnboardingData } from '@/lib/onboarding-types';
import type { ShortlistPlanMap } from '@/lib/shortlist';
import { buildInstitutionalIntelligenceReport } from '@/lib/institutional-intelligence';
import { predictProgrammeDecisions } from '@/lib/predictive-decisions';

export interface ExecutiveCommandCenterInput {
  programmes: Programme[];
  profile?: OnboardingData | null;
  shortlistIds?: string[];
  plans?: ShortlistPlanMap;
}

export interface ExecutiveMetric {
  label: string;
  value: string;
  description: string;
}

export interface ExecutiveAlert {
  title: string;
  severity: 'high' | 'medium' | 'low';
  description: string;
  action: string;
}

export interface ExecutiveCommandCenterSnapshot {
  generatedAt: string;
  metrics: ExecutiveMetric[];
  alerts: ExecutiveAlert[];
  productPriorities: string[];
  pipelineStatus: ExecutiveMetric[];
  institutionalSummary: ExecutiveMetric[];
}

export function buildExecutiveCommandCenterSnapshot(
  input: ExecutiveCommandCenterInput,
): ExecutiveCommandCenterSnapshot {
  const profile = input.profile ?? null;
  const shortlistIds = input.shortlistIds ?? [];
  const plans = input.plans ?? {};
  const predictions = predictProgrammeDecisions(input.programmes, {
    profile,
    shortlistIds,
    plans,
  });
  const institutionalReport = buildInstitutionalIntelligenceReport(input.programmes, [
    {
      profile,
      shortlistIds,
      plans,
    },
  ]);
  const readyPredictions = predictions.filter(
    (prediction) => prediction.decisionStage === 'ready-to-act',
  );
  const highRiskPredictions = predictions.filter(
    (prediction) => prediction.decisionRisk === 'high',
  );

  return {
    generatedAt: new Date().toISOString(),
    metrics: [
      {
        label: 'Programmes tracked',
        value: String(input.programmes.length),
        description: 'Total governed programme records available to ScholarScout.',
      },
      {
        label: 'Shortlisted options',
        value: String(shortlistIds.length),
        description: 'Saved programmes currently informing adaptive and predictive ranking.',
      },
      {
        label: 'Ready decisions',
        value: String(readyPredictions.length),
        description: 'Predictions currently in a ready-to-act stage.',
      },
      {
        label: 'High-risk decisions',
        value: String(highRiskPredictions.length),
        description: 'Predictions that need verification before action.',
      },
    ],
    alerts: buildExecutiveAlerts(predictions, institutionalReport.opportunities.length),
    productPriorities: [
      'Integrate adaptive recommendations into /recommendations.',
      'Display predictive decision probability and risk in the dashboard.',
      'Launch staff-only institutional intelligence UI.',
      'Add transparent marketplace sponsored-pathway safeguards.',
      'Convert investor pitch and dashboard narrative into presentation assets.',
    ],
    pipelineStatus: [
      {
        label: 'CI quality gate',
        value: 'Configured',
        description: 'Typecheck, lint, tests, and web build run on GitHub Actions.',
      },
      {
        label: 'Codex webhook runner',
        value: 'Scaffolded',
        description: 'Issue-labeled Codex job packets can be generated from GitHub webhooks.',
      },
      {
        label: 'Autonomous roadmap',
        value: 'Configured',
        description: 'Roadmap and issue packets are generated by product ops automation.',
      },
    ],
    institutionalSummary: [
      {
        label: 'Demand signals',
        value: String(institutionalReport.activeDemandAreas.length),
        description: 'Top demand categories surfaced for institutional partners.',
      },
      {
        label: 'Support signals',
        value: String(institutionalReport.supportNeeds.length),
        description: 'Support needs institutions can address to improve conversion.',
      },
      {
        label: 'Opportunity alerts',
        value: String(institutionalReport.opportunities.length),
        description: 'Actionable programme, affordability, access, and support opportunities.',
      },
    ],
  };
}

function buildExecutiveAlerts(
  predictions: ReturnType<typeof predictProgrammeDecisions>,
  opportunityCount: number,
): ExecutiveAlert[] {
  const alerts: ExecutiveAlert[] = [];
  const topPrediction = predictions[0];

  if (topPrediction) {
    alerts.push({
      title: 'Most likely student decision identified',
      severity: topPrediction.decisionRisk === 'high' ? 'high' : 'medium',
      description: `${topPrediction.programme.name} is currently the most likely choice at ${topPrediction.choiceProbability}%.`,
      action: topPrediction.likelyNextAction,
    });
  }

  if (opportunityCount > 0) {
    alerts.push({
      title: 'Institutional opportunities available',
      severity: 'medium',
      description: `${opportunityCount} institutional opportunity signal${opportunityCount === 1 ? '' : 's'} can be reviewed.`,
      action: 'Open the institutional intelligence dashboard and prioritize the highest-value action.',
    });
  }

  alerts.push({
    title: 'Build pipeline ready for issue-driven execution',
    severity: 'low',
    description: 'GitHub issue templates, CI, product ops reports, and Codex job packets are in place.',
    action: 'Create or label issues with codex/automation to trigger the next build step.',
  });

  return alerts;
}
