import { Opportunity } from './types'

export const opportunities: Opportunity[] = [
  {
    id: 'college-1',
    name: 'Community College IT Program',
    pathway: 'college',
    locationType: 'near_home',
    interests: ['Technology', 'Engineering'],
    support: ['tutoring', 'financial aid'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Affordable local IT pathway with transfer options and strong academic support.',
    duration: '2 years',
    tuitionEstimate: 9800,
    medianStartingSalary: 48000,
    campusAddress: '1 Community College Way, Buffalo, NY',
    commuteTimeMinutes: 18
  },
  {
    id: 'college-2',
    name: 'State University Business Pathway',
    pathway: 'college',
    locationType: 'in_state',
    interests: ['Business', 'Law'],
    support: ['mentorship', 'financial aid'],
    lowCost: false,
    minGpaBand: '2_2_5',
    description: 'Business-focused four-year pathway with advising and internship support.',
    duration: '4 years',
    tuitionEstimate: 26500,
    medianStartingSalary: 56000,
    campusAddress: '500 State University Plaza, Albany, NY',
    commuteTimeMinutes: 155
  },
  {
    id: 'college-3',
    name: 'Urban Education Transfer Track',
    pathway: 'college',
    locationType: 'near_home',
    interests: ['Education', 'Arts'],
    support: ['tutoring', 'mentorship', 'flex schedule'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Flexible education pathway for students interested in teaching and youth development.',
    duration: '2 years + transfer',
    tuitionEstimate: 11200,
    medianStartingSalary: 45000,
    campusAddress: '85 City Campus Drive, Buffalo, NY',
    commuteTimeMinutes: 22
  },
  {
    id: 'trade-1',
    name: 'Electrical Apprenticeship',
    pathway: 'apprenticeship',
    locationType: 'in_state',
    interests: ['Trades', 'Engineering'],
    support: ['mentorship', 'job placement'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Hands-on paid training pathway into electrical work and union careers.',
    duration: '4 years paid apprenticeship',
    tuitionEstimate: 2500,
    medianStartingSalary: 61000,
    campusAddress: '240 Skilled Trades Blvd, Rochester, NY',
    commuteTimeMinutes: 75
  },
  {
    id: 'trade-2',
    name: 'Advanced Manufacturing Certificate',
    pathway: 'certificate',
    locationType: 'near_home',
    interests: ['Trades', 'Technology', 'Engineering'],
    support: ['job placement', 'financial aid'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Short-term manufacturing training with job placement support.',
    duration: '9 months',
    tuitionEstimate: 6400,
    medianStartingSalary: 50000,
    campusAddress: '120 Innovation Park, Buffalo, NY',
    commuteTimeMinutes: 28
  },
  {
    id: 'trade-3',
    name: 'Construction Skills Pre-Apprenticeship',
    pathway: 'trade',
    locationType: 'near_home',
    interests: ['Trades'],
    support: ['mentorship', 'job placement', 'flex schedule'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Entry pathway into construction and skilled labor opportunities.',
    duration: '6 months',
    tuitionEstimate: 3800,
    medianStartingSalary: 44000,
    campusAddress: '42 Builder Lane, Buffalo, NY',
    commuteTimeMinutes: 20
  },
  {
    id: 'health-1',
    name: 'Practical Nursing Certificate',
    pathway: 'certificate',
    locationType: 'in_state',
    interests: ['Healthcare'],
    support: ['tutoring', 'financial aid'],
    lowCost: false,
    minGpaBand: '2_2_5',
    description: 'Career-focused healthcare credential with licensing preparation.',
    duration: '12 months',
    tuitionEstimate: 21000,
    medianStartingSalary: 59000,
    campusAddress: '77 Health Sciences Road, Syracuse, NY',
    commuteTimeMinutes: 145
  },
  {
    id: 'health-2',
    name: 'Medical Assistant Career Program',
    pathway: 'certificate',
    locationType: 'near_home',
    interests: ['Healthcare'],
    support: ['tutoring', 'job placement'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Short-term allied health training designed for fast workforce entry.',
    duration: '10 months',
    tuitionEstimate: 7800,
    medianStartingSalary: 43000,
    campusAddress: '19 Allied Health Center, Buffalo, NY',
    commuteTimeMinutes: 24
  },
  {
    id: 'creative-1',
    name: 'Online UX Design Certificate',
    pathway: 'certificate',
    locationType: 'online',
    interests: ['Arts', 'Technology'],
    support: ['tutoring', 'flex schedule'],
    lowCost: false,
    minGpaBand: '2_2_5',
    description: 'Remote design-focused certificate for digital product and UX careers.',
    duration: '8 months',
    tuitionEstimate: 14500,
    medianStartingSalary: 62000,
    commuteTimeMinutes: 0,
    exploreUrl: 'https://example.com/programs/ux-design',
    applyUrl: 'https://example.com/apply/ux-design'
  },
  {
    id: 'creative-2',
    name: 'Digital Media Bootcamp',
    pathway: 'certificate',
    locationType: 'online',
    interests: ['Arts', 'Technology', 'Business'],
    support: ['mentorship', 'flex schedule'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Project-based digital media training with portfolio development.',
    duration: '6 months',
    tuitionEstimate: 6900,
    medianStartingSalary: 46000,
    commuteTimeMinutes: 0,
    exploreUrl: 'https://example.com/programs/digital-media'
  },
  {
    id: 'law-1',
    name: 'Paralegal Studies Program',
    pathway: 'college',
    locationType: 'in_state',
    interests: ['Law', 'Business'],
    support: ['tutoring', 'mentorship'],
    lowCost: false,
    minGpaBand: '2_2_5',
    description: 'Legal studies pathway with practical office and court-support training.',
    duration: '2 years',
    tuitionEstimate: 23200,
    medianStartingSalary: 47000,
    campusAddress: '300 Justice Square, New York, NY',
    commuteTimeMinutes: 165
  },
  {
    id: 'military-1',
    name: 'Military Career Readiness Track',
    pathway: 'military',
    locationType: 'anywhere',
    interests: ['Engineering', 'Healthcare', 'Technology'],
    support: ['mentorship', 'job placement', 'financial aid'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Service-oriented pathway with training, career structure, and education benefits.',
    duration: 'Varies by branch',
    tuitionEstimate: 0,
    medianStartingSalary: 42000,
    commuteTimeMinutes: 0,
    exploreUrl: 'https://example.com/programs/military-readiness'
  },
  {
    id: 'online-1',
    name: 'Remote Customer Support Certificate',
    pathway: 'certificate',
    locationType: 'online',
    interests: ['Business', 'Technology'],
    support: ['flex schedule', 'job placement'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Remote-ready certificate for students seeking flexible work options.',
    duration: '4 months',
    tuitionEstimate: 3200,
    medianStartingSalary: 39000,
    commuteTimeMinutes: 0,
    applyUrl: 'https://example.com/apply/customer-support'
  },
  {
    id: 'online-2',
    name: 'Cybersecurity Foundations Program',
    pathway: 'certificate',
    locationType: 'online',
    interests: ['Technology', 'Engineering'],
    support: ['tutoring', 'mentorship'],
    lowCost: false,
    minGpaBand: '2_5_3',
    description: 'Entry-level cyber training pathway for students pursuing secure tech careers.',
    duration: '10 months',
    tuitionEstimate: 17800,
    medianStartingSalary: 70000,
    commuteTimeMinutes: 0,
    exploreUrl: 'https://example.com/programs/cyber-foundations',
    applyUrl: 'https://example.com/apply/cyber-foundations'
  },
  {
    id: 'business-1',
    name: 'Entrepreneurship Launch Program',
    pathway: 'certificate',
    locationType: 'near_home',
    interests: ['Business', 'Arts'],
    support: ['mentorship', 'flex schedule'],
    lowCost: true,
    minGpaBand: 'below_2',
    description: 'Small-business and startup fundamentals with coaching and flexible delivery.',
    duration: '5 months',
    tuitionEstimate: 5400,
    medianStartingSalary: 45000,
    campusAddress: '15 Startup Hub Avenue, Buffalo, NY',
    commuteTimeMinutes: 17
  }
]
